export const myCartData = [
  {
    id: 1,
    type: '매수',
    district1: '강남구',
    district2: '압구정동',
    transactionOptions: ['매매', '전세'],
    buildingOptions: ['아파트', '빌라'],
    depositFrom: 1000,
    depositTo: 5000,
    deal: 0.15,
    currentDeal: [],
    status: '진행중',
  },
  {
    id: 2,
    type: '매수',
    district1: '성북구',
    district2: '안암동',
    depositFrom: 5000,
    depositTo: 7000,
    deal: 0.25,
    transactionOptions: ['매매', '전세', '월세'],
    buildingOptions: ['아파트', '빌라', '원룸'],
    currentDeal: [],
    status: '진행중',
  },
  {
    id: 3,
    type: '매도',
    floor: 3,
    area: 24.3,
    deal: 0.35,
    district1: '성북구',
    district2: '정릉동',
    address: '정릉아파트',
    currentDeal: [],
    status: '진행중',
  },
  {
    id: 4,
    type: '매도',
    district1: '강남구',
    district2: '압구정동',
    address: '압구정아파트',
    deal: 0.25,
    floor: 10,
    area: 32,
    currentDeal: [],
    status: '진행중',
  },
]

export const DealData = [
  {
    id: 1,
    name: 'abc 부동산',
    address: '서울시 강남구 압구정동',
    star: 1.5,
    value: 0.5,
    cartId: 4,
  },
  {
    id: 2,
    name: 'fjiejife 부동산',
    address: '서울시 강남구 압구정동',
    star: 3.5,
    value: 0.4,
    cartId: 4,
  },
  {
    id: 3,
    name: 'as12d 부동산',
    address: '서울시 강남구 압구정동',
    star: 4.2,
    value: 0.3,
    cartId: 4,
  },
  {
    id: 4,
    name: 'as12d 부동산',
    address: '서울시 강남구 압구정동',
    star: 4.5,
    value: 0.3,
    cartId: 4,
  },
  {
    id: 5,
    address: '서울시 강남구 압구정동',
    star: 1.5,
    name: 'abc 부동산',
    value: 0.5,
    cartId: 1,
  },
  {
    id: 6,
    address: '서울시 강남구 압구정동',
    star: 1.5,
    name: 'fjiejife 부동산',
    value: 0.4,
    cartId: 1,
  },
  {
    id: 7,
    address: '서울시 강남구 압구정동',
    star: 1.5,
    name: 'asd 부동산',
    value: 0.3,
    cartId: 1,
  },
  {
    id: 8,
    address: '서울시 강남구 압구정동',
    star: 1.5,
    name: 'abc 부동산',
    value: 0.5,
    cartId: 2,
  },
  {
    id: 9,
    address: '서울시 강남구 압구정동',
    star: 1.5,
    name: 'fjiejife 부동산',
    value: 0.4,
    cartId: 2,
  },
  {
    id: 10,
    address: '서울시 강남구 압구정동',
    star: 1.5,
    name: 'as12d 부동산',
    value: 0.3,
    cartId: 2,
  },
  {
    id: 11,
    address: '서울시 강남구 압구정동',
    star: 1.5,
    name: 'as12d 부동산',
    value: 0.3,
    cartId: 2,
  },
  {
    id: 12,
    address: '서울시 강남구 압구정동',
    star: 1.5,
    name: 'as12d 부동산',
    value: 0.3,
    cartId: 2,
  },
  {
    id: 13,
    address: '서울시 강남구 압구정동',
    star: 1.5,
    name: 'abc 부동산',
    value: 0.5,
    cartId: 2,
  },
  {
    id: 14,
    address: '서울시 강남구 압구정동',
    star: 1.5,
    name: 'abc 부동산',
    value: 0.5,
    cartId: 2,
  },
  {
    id: 15,
    address: '서울시 강남구 압구정동',
    star: 1.5,
    name: 'abc 부동산',
    value: 0.5,
    cartId: 2,
  },
  {
    id: 16,
    address: '서울시 강남구 압구정동',
    star: 1.5,
    name: 'abc 부동산',
    value: 0.5,
    cartId: 2,
  },
  {
    id: 17,
    address: '서울시 강남구 압구정동',
    star: 1.5,
    name: 'abc 부동산',
    value: 0.5,
    cartId: 2,
  },
  {
    id: 18,
    address: '서울시 강남구 압구정동',
    star: 1.5,
    name: 'abc 부동산',
    value: 0.5,
    cartId: 2,
  },
]
