export const KCData = [
  {
    id: 1,
    date: 20190920,
    district1: '성북구',
    district2: '안암동',
    buildingType: '아파트',
    transactionType: '전세',
    saved: 100,
    comment:
      '투자부동산 전문 투자자가 소개하는 실전 부자 공부 노하우를 지금 확인해보세요. ... 부동산을 거래하면 세금이 발생합니다. ',
  },
  {
    id: 2,
    date: 20190920,
    district1: '동대문구',
    district2: '용두동',
    buildingType: '아파트',
    transactionType: '전세',
    saved: 250,
    comment: '너무너무 좋아요~',
  },
  {
    id: 3,
    date: 20190920,
    district1: '종로구',
    district2: '숭인2동',
    buildingType: '빌라',
    transactionType: '매매',
    saved: 150,
    comment: '너무너무 좋아요~',
  },
  {
    id: 4,
    date: 20190920,
    district1: '성북구',
    district2: '안암동',
    buildingType: '아파트',
    transactionType: '전세',
    saved: 100,
    comment: '너무너무 좋아요~',
  },
]
